[book]
authors = ["test"]
language = "en"
multilingual = false
src = "src"
title = "my little world"

[preprocessor]

[preprocessor.graphviz]
command = "mdbook-graphviz"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.image-size]
command = "mdbook-image-size"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
